### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LittleBlueGamer427** [GetTurboLive/extension#2]
![image](https://github.com/GetTurboLive/extension/assets/148423893/f71ce6ff-4c09-4720-a46c-e6975340c020)

**Comment by daydreamyyZX** [comment]
> ![image](https://private-user-images.githubusercontent.com/148423893/317068899-f71ce6ff-4c09-4720-a46c-e6975340c020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0OTgxODUsIm5iZiI6MTcxMTQ5Nzg4NSwicGF0aCI6Ii8xNDg0MjM4OTMvMzE3MDY4ODk5LWY3MWNlNmZmLTRjMDktNDcyMC1hNDZjLWU2OTc1MzQwYzAyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwMDA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDI1YzQzMjU0MzZlZWQ2OWJlYjE4NDBmZTI2YzQ3MWFmMWZjZDM3MzJmNzg1MjZjYzZlZWFmMWY1OTM0YjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rVgYTr5dF5ypnsyoPkq9wq9KuLzNfLvQ74f_cTKLbjw)

turbolive's last update was september
i don't think it was made with being polished in mind
it barely worked before the co-founder left

**Comment by AtomicInitial** [comment]
> ![image](https://private-user-images.githubusercontent.com/148423893/317068899-f71ce6ff-4c09-4720-a46c-e6975340c020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNzI5ODcsIm5iZiI6MTcyODE3MjY4NywicGF0aCI6Ii8xNDg0MjM4OTMvMzE3MDY4ODk5LWY3MWNlNmZmLTRjMDktNDcyMC1hNDZjLWU2OTc1MzQwYzAyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQyMzU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjcwMzFjYzc1ZTI5M2FlYjAxZWI0YTBjYWE4ZjBlOWY3ODQ5YWZkZDJkZDNkNWE1NmM3MmJiOWUxNjU3NTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MJ-Q2GJqnIg1M4jLzO9R9f__90UeFd2_7CST9U23bNQ)

Very late reply, but this is when TurboLive's foundations were first created. The extension files were created for use in our own environments, due to some weird complications with unreleased chrome extensions. This is why it doesnt work for general use, we never updated.
